package com.dev.ecommerceuser.rest

class ApiUtils {
    companion object{
        const val DeviceType:String="2"
        const val Register:String="register"
        const val LOGIN:String = "login"
        const val ForgotPassword:String = "forgotPassword"
        const val VerifyAccount:String = "verifyAccount"
        const val ChangePassword:String = "changePassword"
        const val ResendOtp:String = "resendOtp"
        const val ResetPassword:String = "resetPassword"
        const val GetCountries:String = "getCountries"
        const val GetProfile:String = "getProfile"
        const val EditProfile:String = "editProfile"
        const val GetHomes:String = "getHomes"
        const val GetCategories:String = "getCategories"
        const val GetNamesAndCategories:String = "getNamesAndCategories"
        const val GetNotifications:String = "getNotifications"
        const val NotificationDelete:String = "notificationDelete"
        const val ContactUs:String = "contactUs"
        const val LikeUnlike:String = "likeUnlike"
        const val LikeUnlikeProduct:String = "likeUnlikeProduct"
        const val GetGlobalMarket:String = "getGlobalMarket"
        const val GetGlobalMarketSuppliers:String = "getGlobalMarketSuppliers"
        const val GetOffersAndDiscounts:String = "getOffersAndDiscounts"
        const val SupplierDetails:String = "supplierDetails"
        const val GetGallery:String = "getGallery"
        const val GetFavouritesSuppliersAndProducts:String = "getFavouritesSuppliersAndProducts"
        const val AddLocations:String = "addLocations"
        const val MyLocations:String = "myLocations"
        const val DeleteLocation:String = "deleteLocation"
        const val ChnageNotificationStatus:String = "chnageNotificationStatus"
        const val ProductDetailPage:String = "productDetailPage"
        const val GetProducts:String = "getProducts"
        const val CheckProductAvailable:String = "checkProductAvailable"
        const val CheckProductPrice:String = "checkProductPrice"
        const val AddCards:String = "addCards"
        const val MyCards:String = "myCards"
        const val DeleteCard:String = "deleteCard"
        const val CartAdd:String = "cartAdd"
        const val MyCart:String = "myCart"
        const val PlaceOrder:String = "createCharge"
        const val MyOrder:String = "myOrder"
        const val GetCoupons:String = "getCoupons"
        const val ApplyCoupons:String = "applyCoupons"
        const val GetTermsConditions:String = "getTermsConditions"
        const val GetPrivacyPolicy:String = "getPrivacyPolicy"
        const val GetAboutUs:String = "getAboutUs"
        const val GetFaq:String = "getFaq"
        const val MakeDefaultLocation:String = "makeDefaultLocation"
        const val SEARCHFILTER = "searchFilter"
        const val ACCOUNTTYPE = "getAccountTypes"
    }
}